extends: default
rules:
  document-start: disable
  line-length: disable
  indentation:
    spaces: consistent
    indent-sequences: consistent
  truthy:
    check-keys: false
  braces:
    max-spaces-inside: 1
