ruleDirs:
  - rules/bash
  - rules/c
  - rules/go
  - rules/java
  - rules/javascript
  - rules/lua
  - rules/php
  - rules/python
languageGlobs:
  php:
    - '*.php'
    - '*.phtml'
testConfigs:
  - testDir: tests
