ruleDirs:
  - rules/bash
  - rules/c
  - rules/cpp
  - rules/csharp
  - rules/go
  - rules/html
  - rules/java
  - rules/javascript
  - rules/kotlin
  - rules/lua
  - rules/php
  - rules/python
  - rules/ruby
  - rules/rust
  - rules/scala
  - rules/swift
  - rules/typescript
languageGlobs:
  php:
    - '*.php'
    - '*.phtml'
testConfigs:
  - testDir: tests
